### 1. New user registration 
POST http://localhost:5003/auth/register
Content-Type: application/json

{
  "username": "testuser",
  "password": "TestPassword123"
}

### 2. Successful login
POST http://localhost:5003/auth/login
Content-Type: application/json

{
  "username": "testuser",
  "password": "TestPassword123"
}

### 3. Incorrect login (after 5 attempts will block the user)
POST http://localhost:5003/auth/login
Content-Type: application/json

{
  "username": "testuser",
  "password": "wrongPassword"
}

### 8. Try to login with the same credentials again (should fail)   
POST http://localhost:5003/auth/login
Content-Type: application/json

{
  "username": "testuser",
  "password": "TestPassword123"
}
