### 1. New user registration 
POST http://localhost:5003/auth/register
Content-Type: application/json

{
  "username": "ObiWanKenobi",
  "password": "TestPassword123"
}

### 2. Successful login
POST http://localhost:5003/auth/login
Content-Type: application/json

{
  "username": "ObiWanKenobi",
  "password": "TestPassword123"
}


### 3. Change password
POST http://localhost:5003/auth/change-password
Content-Type: application/json
Cookie: token={token}

{
  "currentPassword": "TestPassword123",
  "newPassword": "newSecurePassword456"
}
 