### 1. New user registration 
POST http://localhost:5003/auth/register
Content-Type: application/json

{
  "username": "ObiWanKenobi",
  "password": "TestPassword123"
}

### 2. Successful login
POST http://localhost:5003/auth/login
Content-Type: application/json

{
  "username": "ObiWanKenobi",
  "password": "TestPassword123"
}


### 3. Change password
POST http://localhost:5003/auth/change-password
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4M2QyMTY3Y2IwNDQ1MzRkMTk4ZDY0OSIsInVzZXJuYW1lIjoiT2JpV2FuS2Vub2JpIiwiaWF0IjoxNzQ4ODM3ODM4LCJleHAiOjE3NDg4NDE0Mzh9.GIR0xt3-nHj9ytCoe5aKX8qM34MNKEg6tYGM2GkkSg4

{
  "currentPassword": "TestPassword123",
  "newPassword": "newSecurePassword456"
}
