### Login admin
POST http://localhost:5003/auth/login
Content-Type: application/json

{
  "username": "userAdmin",
  "password": "admin123"
}

### Role protected route
GET http://localhost:5003/auth/all
Cookie: token={token}

