### Register a new user
POST http://localhost:5003/auth/register
Content-Type: application/json

{
  "username": "juan4",
  "password": "123456"
}

### login a user
POST http://localhost:5003/auth/login
Content-Type: application/json

{
  "username": "juan3",
  "password": "123456"
}

### Protected route with token
GET http://localhost:5003/auth/profile
Authorization: Bearer {token}

### Refresh access token
POST http://localhost:5003/auth/refresh
Cookie: refreshToken={refreshToken}

